### ISSUE TITLE
Tip: Showing time in the keyword previews

### ISSUE THREAD

**Issue by vitorgalvao** [andreatitolo/kya-alfred#1]
Just like you’re using `{var:}` for the keywords themselves, you can use similar methods to show richer results. For example: instead of having `ka` say the computer will be kept awake `for set hours`, you can have them show directly:

<img width="598" src="https://github.com/andreatitolo/kya-alfred/assets/1699443/07540da1-b1cd-4311-b832-27b77517253d">

<img width="625" src="https://github.com/andreatitolo/kya-alfred/assets/1699443/b43aa0c7-0537-4533-aee6-951095b52d1a">

And in `kh` and `km`, you can use `{query}` instead of `x`:

<img width="598" src="https://github.com/andreatitolo/kya-alfred/assets/1699443/34e3c38c-9002-4c39-b0bf-dbd7d30b2bf6">

<img width="625" src="https://github.com/andreatitolo/kya-alfred/assets/1699443/2fb79299-81f5-4dac-b45e-465f32a415c9">

**Comment by andreatitolo** [comment]
Thanks for the suggestion! I'm uploading a new version with {var:} and {query} for richer output :)
